# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Coffee(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, price: float=None, description: str=None):  # noqa: E501
        """Coffee - a model defined in Swagger

        :param id: The id of this Coffee.  # noqa: E501
        :type id: int
        :param name: The name of this Coffee.  # noqa: E501
        :type name: str
        :param price: The price of this Coffee.  # noqa: E501
        :type price: float
        :param description: The description of this Coffee.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'price': float,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'price': 'price',
            'description': 'description'
        }
        self._id = id
        self._name = name
        self._price = price
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Coffee':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coffee of this Coffee.  # noqa: E501
        :rtype: Coffee
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Coffee.


        :return: The id of this Coffee.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Coffee.


        :param id: The id of this Coffee.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Coffee.


        :return: The name of this Coffee.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Coffee.


        :param name: The name of this Coffee.
        :type name: str
        """

        self._name = name

    @property
    def price(self) -> float:
        """Gets the price of this Coffee.


        :return: The price of this Coffee.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Coffee.


        :param price: The price of this Coffee.
        :type price: float
        """

        self._price = price

    @property
    def description(self) -> str:
        """Gets the description of this Coffee.


        :return: The description of this Coffee.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Coffee.


        :param description: The description of this Coffee.
        :type description: str
        """

        self._description = description
