# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, coffee_id: int=None, quantity: int=None, price: float=None):  # noqa: E501
        """OrderItem - a model defined in Swagger

        :param coffee_id: The coffee_id of this OrderItem.  # noqa: E501
        :type coffee_id: int
        :param quantity: The quantity of this OrderItem.  # noqa: E501
        :type quantity: int
        :param price: The price of this OrderItem.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'coffee_id': int,
            'quantity': int,
            'price': float
        }

        self.attribute_map = {
            'coffee_id': 'coffeeId',
            'quantity': 'quantity',
            'price': 'price'
        }
        self._coffee_id = coffee_id
        self._quantity = quantity
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'OrderItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrderItem of this OrderItem.  # noqa: E501
        :rtype: OrderItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def coffee_id(self) -> int:
        """Gets the coffee_id of this OrderItem.


        :return: The coffee_id of this OrderItem.
        :rtype: int
        """
        return self._coffee_id

    @coffee_id.setter
    def coffee_id(self, coffee_id: int):
        """Sets the coffee_id of this OrderItem.


        :param coffee_id: The coffee_id of this OrderItem.
        :type coffee_id: int
        """

        self._coffee_id = coffee_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this OrderItem.


        :return: The quantity of this OrderItem.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this OrderItem.


        :param quantity: The quantity of this OrderItem.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def price(self) -> float:
        """Gets the price of this OrderItem.


        :return: The price of this OrderItem.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this OrderItem.


        :param price: The price of this OrderItem.
        :type price: float
        """

        self._price = price
